### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/isi3-singleton-mounier-jolivet-tp5#1]
- [x] En quoi l'expression que vous avez employé n'a aucun sens "compilé au runtime" ?

- [x] L'autowiring permet d'injecter un bean automatiquement par nom ou type. On peut faire de l'autowiring en configuration XML. Je vous laisse me donner ici la configuration qu'il faudrait faire.

- [x] Pour la gestion des différentes configuration avec Spring, il y a une notion de "Profile" qui est plus élégante et plus pérenne que votre solution avec le If. Voici de la documentation pour vous aider à l'implémenter correctement.

https://jeanchristophegay.com/spring-et-les-profils/

**Comment by mounieju** [comment]
1. Ah! Effectivement, je pense que c'est une faute d'inattention (vu qu'on voulait dire qu'elles pouvaient être exécutées à la compilation et au runtime). Ca n'a en effet pas de sens car ce sont deux choses différentes : Dans un premier temps, le code source doit être compilé en code machine pour devenir programme exécutable (compilation), et une fois ce programme compilé, il peut être ouvert et exécuté par un utilisateur (runtime).
<br/>

2. Pour faire de l'autowiring en configuration XML, il faut utiliser l'attribut `autowire` dans la balise `bean`.
- `autowire = "byName"`: Autowiring utilisant le nom de la propriété. S'il existe un bean avec le même nom que la propriété d'un autre bean, il sera alors lié.
- `autowire = "byType"`: Idem, avec le même type que le type de propriété d'un autre bean. <br/>
Ici pour le projet, comme notre interface Loggable possède un attribut de type Logger et de nom "logger", on doit donc le binder par nom car ce n'est pas le même type que le bean "logger" : 
 `<bean name="loggable" class="loggable.Loggable" autowire=byName />`
`<bean name="logger" class="logger.ConsoleLogger" scope="prototype"/>`

3. Nous le modifierons.

**Comment by mounieju** [comment]
Bonjour, 
Nous avons mis en place la gestion de profiles, pourrez-vous nous dire ce que vous en pensez ? 
Merci !

**Comment by Slashgear** [comment]
👌
